In [1]:
import numpy as np
import pandas as pd
import random
import time
from unidecode import unidecode
from datetime import datetime, timedelta

In [3]:
today=current_date = datetime.now()
months_dict={1:'january',2:'february',3:'march',4:'april',5:'may',6:'june',7:'july',8:'august',9:'september',10:'october',11:'november',12:'december'}

In [5]:
schedule_df=pd.DataFrame()
month=months_dict[today.month]
url='https://www.basketball-reference.com/leagues/NBA_2025_games-'+month+'.html'
schedule_df=pd.read_html(url,header=0,attrs={'id':'schedule'})[0]
schedule_df=schedule_df[schedule_df['PTS']!='PTS']
schedule_df.drop(columns=['Unnamed: 6','Unnamed: 7','Notes'],inplace=True)
schedule_df['Date'] = pd.to_datetime(schedule_df['Date'])
schedule_df

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Attend.,LOG,Arena
0,2024-12-01,3:30p,Orlando Magic,100.0,Brooklyn Nets,92.0,16505.0,2:36,Barclays Center
1,2024-12-01,3:30p,Indiana Pacers,121.0,Memphis Grizzlies,136.0,15901.0,2:18,FedEx Forum
2,2024-12-01,6:00p,Boston Celtics,111.0,Cleveland Cavaliers,115.0,19432.0,2:16,Rocket Mortgage Fieldhouse
3,2024-12-01,6:00p,New Orleans Pelicans,85.0,New York Knicks,118.0,19812.0,2:03,Madison Square Garden (IV)
4,2024-12-01,6:00p,Miami Heat,116.0,Toronto Raptors,119.0,18153.0,2:16,Scotiabank Arena
...,...,...,...,...,...,...,...,...,...
182,2024-12-31,3:00p,Milwaukee Bucks,NaN,Indiana Pacers,NaN,NaN,NaN,Gainbridge Fieldhouse
183,2024-12-31,7:00p,Los Angeles Clippers,NaN,San Antonio Spurs,NaN,NaN,NaN,Frost Bank Center
184,2024-12-31,8:00p,Minnesota Timberwolves,NaN,Oklahoma City Thunder,NaN,NaN,NaN,Paycom Center
185,2024-12-31,9:00p,Cleveland Cavaliers,NaN,Los Angeles Lakers,NaN,NaN,NaN,Crypto.com Arena
186,2024-12-31,9:00p,Memphis Grizzlies,NaN,Phoenix Suns,NaN,NaN,NaN,Footprint Center

In [7]:
current_date = datetime.now().date()
next_day = current_date + timedelta(days=1)
upcoming_games = schedule_df[schedule_df['Date'] == pd.Timestamp(current_date)]
if upcoming_games['PTS'].isnull().sum()==0:
    upcoming_games = schedule_df[schedule_df['Date'] == pd.Timestamp(next_day)]
upcoming_games

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Attend.,LOG,Arena
46,2024-12-07,1:00p,Cleveland Cavaliers,NaN,Charlotte Hornets,NaN,NaN,NaN,Spectrum Center
47,2024-12-07,7:00p,Oklahoma City Thunder,NaN,New Orleans Pelicans,NaN,NaN,NaN,Smoothie King Center
48,2024-12-07,7:00p,Denver Nuggets,NaN,Washington Wizards,NaN,NaN,NaN,Capital One Arena
49,2024-12-07,7:30p,Detroit Pistons,NaN,New York Knicks,NaN,NaN,NaN,Madison Square Garden (IV)
50,2024-12-07,7:30p,Dallas Mavericks,NaN,Toronto Raptors,NaN,NaN,NaN,Scotiabank Arena
51,2024-12-07,8:00p,Memphis Grizzlies,NaN,Boston Celtics,NaN,NaN,NaN,TD Garden
52,2024-12-07,8:00p,Phoenix Suns,NaN,Miami Heat,NaN,NaN,NaN,Kaseya Center

In [9]:
teams={'Atlanta Hawks':'ATL','Boston Celtics':'BOS','Brooklyn Nets':'BRK','Charlotte Hornets':'CHO','Chicago Bulls':'CHI','Cleveland Cavaliers':'CLE',
       'Dallas Mavericks':'DAL','Denver Nuggets':'DEN','Detroit Pistons':'DET',
        'Golden State Warriors':'GSW','Houston Rockets':'HOU','Indiana Pacers':'IND','Los Angeles Clippers':'LAC','Los Angeles Lakers':'LAL',
       'Memphis Grizzlies':'MEM','Miami Heat':'MIA','Milwaukee Bucks':'MIL','Minnesota Timberwolves':'MIN','New Orleans Pelicans':'NOP',
       'New York Knicks':'NYK','Oklahoma City Thunder':'OKC','Orlando Magic':'ORL','Philadelphia 76ers':'PHI','Phoenix Suns':'PHO','Portland Trail Blazers':'POR',
       'Sacramento Kings':'SAC','San Antonio Spurs':'SAS','Toronto Raptors':'TOR','Utah Jazz':'UTA','Washington Wizards':'was'}
len(teams)

30

In [11]:
game=int(input('Enter game no. '))
print("Home side: "+upcoming_games.iloc[game-1]['Home/Neutral']+" | Road side: "+upcoming_games.iloc[game-1]['Visitor/Neutral'])
HorR=input('Enter H for the home side and R for the road side: ')
team=None
if (HorR == 'H'):
    teamname=upcoming_games.iloc[game-1]['Home/Neutral']
    team=teams[teamname]
    opponent=teams[upcoming_games.iloc[game-1]['Visitor/Neutral']]
elif (HorR == 'R'):
    teamname=upcoming_games.iloc[game-1]['Visitor/Neutral']
    team=teams[teamname]
    opponent=teams[upcoming_games.iloc[game-1]['Home/Neutral']]
else:
    print('Invalid choice')

if team is not None:
    url='https://www.basketball-reference.com/teams/'+team+'/2025.html'
    roster_df=pd.read_html(url,header=0,attrs={'id':'roster'})[0]
roster_df.drop(columns=['Birth'],inplace=True)
roster_df

Enter game no.  5

Home side: Toronto Raptors | Road side: Dallas Mavericks

Enter H for the home side and R for the road side:  R

,No.,Player,Pos,Ht,Wt,Birth Date,Exp,College
0,21.0,Daniel Gafford,C,6-10,234,"October 1, 1998",5,Arkansas
1,1.0,Jaden Hardy,SG,6-4,198,"July 5, 2002",2,NaN
2,11.0,Kyrie Irving,SG,6-2,195,"March 23, 1992",13,Duke
3,5.0,Quentin Grimes,SG,6-5,205,"May 8, 2000",3,"Kansas, Houston"
4,26.0,Spencer Dinwiddie,PG,6-5,215,"April 6, 1993",10,Colorado
5,13.0,Naji Marshall,SF,6-7,220,"January 24, 1998",4,Xavier
6,31.0,Klay Thompson,SF,6-5,215,"February 8, 1990",11,Washington State
7,25.0,P.J. Washington,PF,6-7,230,"August 23, 1998",5,Kentucky
8,2.0,Dereck Lively II,C,7-1,230,"February 12, 2004",1,Duke
9,77.0,Luka Dončić,PG,6-6,230,"February 28, 1999",6,NaN
10,7.0,Dwight Powell,C,6-10,240,"July 20, 1991",10,Stanford
11,42.0,Maxi Kleber,PF,6-10,240,"January 29, 1992",7,NaN
12,8.0,Olivier-Maxence Prosper,PF,6-8,230,"July 3, 2002",1,"Clemson, Marquette"
13,0.0,Jazian Gortman (TW),PG,6-2,184,"April 14, 2003",R,NaN
14,10.0,Brandon Williams (TW),PG,6-1,190,"November 22, 1999",2,Arizona
15,20.0,Kessler Edwards (TW),SF,6-8,215,"August 9, 2000",3,Pepperdine
16,88.0,Markieff Morris,PF,6-9,245,"September 2, 1989",13,Kansas
17,NaN,Dante Exum,PG,6-5,214,"July 13, 1995",7,NaN

In [13]:
import requests
from bs4 import BeautifulSoup

def validate_player_details(url, expected_team, expected_jersey):
    # Fetch the web page content
    response = requests.get(url)
    if response.status_code != 200:
        print(f"Failed to fetch the page. Status code: {response.status_code}")
        return False

    # Parse the page content
    soup = BeautifulSoup(response.content, 'html.parser')

    # Extract the team name
    team_tag = soup.select_one('#meta strong:contains("Team") + a')
    team_name = team_tag.text.strip() if team_tag else None

    # Extract all jersey numbers from SVG elements
    svg_tags = soup.find_all('svg', class_='jersey')  # Find all SVG elements containing jersey numbers
    jersey_number = None
    if svg_tags:
        # The last SVG element corresponds to the current team's jersey number
        last_svg = svg_tags[-1]
        # Extract the text from <text> tags within the last SVG
        text_tags = last_svg.find_all('text')
        jersey_number = ''.join([tag.text.strip() for tag in text_tags])

    # Print and compare the results
    #print(f"Team Name on page: {team_name}, Jersey Number on page: {jersey_number}")
    return team_name == expected_team and jersey_number == expected_jersey

In [15]:
import requests
from bs4 import BeautifulSoup

def extract_defensive_rating(team):
    # Send a GET request to the page
    url='https://www.basketball-reference.com/teams/'+team+'/2025.html'
    response = requests.get(url)
    if response.status_code != 200:
        print(f"Failed to fetch the page. Status code: {response.status_code}")
        return None

    # Parse the HTML content
    soup = BeautifulSoup(response.content, 'html.parser')

    # Look for the "Def Rtg" label in the stats section
    stats_section = soup.find('div', id='info')  # Restrict search to the stats info section
    if not stats_section:
        print("Could not find the stats section.")
        return None

    # Search for "Def Rtg" text within the stats section
    for strong_tag in stats_section.find_all('strong'):
        if "Def Rtg" in strong_tag.text:
            # Extract the value after "Def Rtg:"
            def_rtg_value = strong_tag.next_sibling.strip()
            return def_rtg_value.split()[1]

    print("Defensive Rating not found on the page.")
    return None

In [35]:
player=int(input("Enter player index no. "))
print('Pos: '+roster_df.iloc[player-1]['Pos'])
print('Name: '+roster_df.iloc[player-1]['Player'])
print('Height: '+roster_df.iloc[player-1]['Ht'])
name=roster_df.iloc[player-1]['Player']
l=name.split()
num=1
name=l[1][:5]+l[0][:2]+'01'
for i in range(len(name)):
    if name[i]=='ö':
        name=name[:i]+'o'+name[i+1:]
url='https://www.basketball-reference.com/players/t/'+name+'/gamelog/2025'
jerseyno=str(int(roster_df.iloc[player-1]['No.']))
while(validate_player_details(url, teamname, jerseyno)==False):
    num+=1
    if num<10:
        name=l[1][:5]+l[0][:2]+'0'+str(num)
    else:
        name=l[1][:5]+l[0][:2]+str(num)
    url=url='https://www.basketball-reference.com/players/t/'+name+'/gamelog/2025'
player_gamelog=pd.read_html(url,header=0,attrs={'id':'pgl_basic'})[0]
player_gamelog.drop(columns=['Rk','G','Age','Unnamed: 5'],inplace=True)
player_gamelog.rename(columns={'Tm':'Team','Unnamed: 7':'Result'},inplace=True)
player_gamelog['Opp DefRtg'] = player_gamelog['Opp'].apply(lambda opp: extract_defensive_rating(opp))
player_gamelog

Enter player index no.  2

Pos: SG
Name: Jaden Hardy
Height: 6-4
Failed to fetch the page. Status code: 404

,Date,Team,Opp,Result,GS,MP,FG,FGA,FG%,3P,...,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,Opp DefRtg
0,2024-10-24,DAL,SAS,W (+11),0,19:40,3,6,.500,3,...,1,2,0,1,2,3,11,7.6,-5,113.5
1,2024-10-26,DAL,PHO,L (-12),0,13:16,0,4,.000,0,...,1,0,0,0,0,1,0,-2.9,-1,115.1
2,2024-10-28,DAL,UTA,W (+8),0,5:10,0,1,.000,0,...,0,0,0,0,1,1,0,-2.1,-4,120.1
3,2024-10-29,DAL,MIN,W (+6),0,4:25,1,1,1.000,0,...,1,1,0,0,1,0,2,1.7,+3,109.1
4,2024-10-31,DAL,HOU,L (-6),0,11:16,1,3,.333,0,...,2,1,1,0,1,2,2,1.2,+10,105.6
5,2024-11-03,DAL,ORL,W (+23),0,8:34,1,3,.333,1,...,1,0,0,0,3,1,3,-1.8,-8,106.1
6,2024-11-04,DAL,IND,L (-7),Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,117.3
7,2024-11-06,DAL,CHI,W (+20),0,13:29,4,10,.400,3,...,0,2,0,0,1,1,11,5.6,-5,117.9
8,2024-11-08,DAL,PHO,L (-1),0,3:29,0,0,NaN,0,...,0,0,0,0,0,0,0,0.0,-1,115.1
9,2024-11-10,DAL,DEN,L (-2),0,18:35,1,7,.143,0,...,2,3,1,0,1,1,2,0.2,0,115.0
10,2024-11-12,DAL,GSW,L (-3),0,18:57,1,2,.500,0,...,2,4,1,0,1,1,4,6.0,+16,108.4
11,2024-11-14,DAL,UTA,L (-2),0,22:05,3,6,.500,0,...,2,1,3,0,3,2,7,4.9,-8,120.1
12,2024-11-16,DAL,SAS,W (+17),0,18:30,4,9,.444,2,...,3,1,0,0,0,3,12,7.7,+5,113.5
13,2024-11-17,DAL,OKC,W (+2),0,24:06,6,9,.667,0,...,3,1,1,0,2,3,13,8.5,+6,103.7
14,2024-11-19,DAL,NOP,W (+41),0,19:20,4,12,.333,0,...,2,3,0,0,1,1,11,5.5,+13,118.6
15,2024-11-22,DAL,DEN,W (+3),0,13:14,3,9,.333,1,...,0,2,0,0,1,1,8,2.5,-16,115.0
16,2024-11-24,DAL,MIA,L (-5),0,9:15,0,3,.000,0,...,0,1,1,0,1,2,0,-2.2,-10,111.4
17,2024-11-25,DAL,ATL,W (+10),1,32:07,8,18,.444,2,...,3,2,3,0,6,2,23,11.3,-6,114.2
18,2024-11-27,DAL,NYK,W (+15),0,15:50,1,5,.200,1,...,1,0,0,0,1,0,5,1.2,+14,114.4
19,2024-11-30,DAL,UTA,W (+12),0,16:15,1,7,.143,0,...,2,2,2,0,3,3,4,-0.7,+1,120.1
20,Date,Tm,Opp,NaN,GS,MP,FG,FGA,FG%,3P,...,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,None
21,2024-12-01,DAL,POR,W (+6),1,23:29,5,12,.417,3,...,3,1,1,0,0,1,13,8.8,-9,115.8
22,2024-12-03,DAL,MEM,W (+5),0,3:35,0,0,NaN,0,...,0,0,0,0,2,0,0,-2.0,-1,108.6
23,2024-12-05,DAL,WAS,W (+36),0,5:38,5,6,.833,2,...,1,0,0,0,0,1,13,10.7,+7,120.6

In [37]:
tgl_df=pd.DataFrame()
url='https://www.basketball-reference.com/teams/'+team+'/2025/gamelog/'
tgl_df=pd.read_html(url,header=1,attrs={'id':'tgl_basic'})[0]
tgl_df=tgl_df[['FG%','3P%','TRB','AST','STL','BLK']]
tgl_df.rename(columns={'FG%':'Team_FG%','3P%':'Team_3P%','TRB':'Team_TRB','AST':'Team_AST','STL':'Team_STL','BLK':'Team_BLK'},inplace=True)
#player_gamelog = pd.concat([player_gamelog, tgl_df], axis=1)
tgl_df

   Team_FG% Team_3P% Team_TRB Team_AST Team_STL Team_BLK
0      .412     .432       50       27        9        5
1      .398     .317       46       22        6        2
2      .453     .282       50       27        9       12
3      .484     .410       40       25       12        2
4      .459     .333       37       21        6        7
5      .494     .313       53       25        8        5
6      .517     .417       38       29        4        3
7      .484     .316       47       33       11        4
8      .513     .333       39       18        5        1
9      .533     .303       42       29        7        5
10     .524     .324       40       26        6        1
11     .506     .308       30       25       11       10
12     .468     .258       53       26        9        7
13     .476     .407       53       18        4        5
14     .521     .452       48       26       12        7
15     .505     .370       44       24       11        5
16     .419     .250       59       29        6        9
17     .500     .457       51       24        6        8
18     .565     .515       43       27        6        4
19     .456     .385       48       30       12        6
20     Team     Team     Team     Team     Team     Team
21      FG%      3P%      TRB      AST      STL      BLK
22     .552     .500       33       33       13        0
23     .481     .406       49       24        8        8
24     .539     .526       58       27        8       12

In [25]:
tgl_df = tgl_df[(tgl_df['Team_FG%'] != 'Team') & (tgl_df['Team_FG%'] != 'FG%')].reset_index(drop=True)
tgl_df

   Team_FG% Team_3P% Team_TRB Team_AST Team_STL Team_BLK
0      .412     .432       50       27        9        5
1      .398     .317       46       22        6        2
2      .453     .282       50       27        9       12
3      .484     .410       40       25       12        2
4      .459     .333       37       21        6        7
5      .494     .313       53       25        8        5
6      .517     .417       38       29        4        3
7      .484     .316       47       33       11        4
8      .513     .333       39       18        5        1
9      .533     .303       42       29        7        5
10     .524     .324       40       26        6        1
11     .506     .308       30       25       11       10
12     .468     .258       53       26        9        7
13     .476     .407       53       18        4        5
14     .521     .452       48       26       12        7
15     .505     .370       44       24       11        5
16     .419     .250       59       29        6        9
17     .500     .457       51       24        6        8
18     .565     .515       43       27        6        4
19     .456     .385       48       30       12        6
22     .552     .500       33       33       13        0
23     .481     .406       49       24        8        8
24     .539     .526       58       27        8       12

In [29]:
player_gamelog=player_gamelog[player_gamelog['GS']!='GS'].reset_index(drop=True)
player_gamelog

,Date,Team,Opp,Result,GS,MP,FG,FGA,FG%,3P,...,TRB,AST,STL,BLK,TOV,PF,PTS,GmSc,+/-,Opp DefRtg
0,2024-10-24,DAL,SAS,W (+11),0,19:40,3,6,.500,3,...,1,2,0,1,2,3,11,7.6,-5,113.5
1,2024-10-26,DAL,PHO,L (-12),0,13:16,0,4,.000,0,...,1,0,0,0,0,1,0,-2.9,-1,115.1
2,2024-10-28,DAL,UTA,W (+8),0,5:10,0,1,.000,0,...,0,0,0,0,1,1,0,-2.1,-4,120.1
3,2024-10-29,DAL,MIN,W (+6),0,4:25,1,1,1.000,0,...,1,1,0,0,1,0,2,1.7,+3,109.1
4,2024-10-31,DAL,HOU,L (-6),0,11:16,1,3,.333,0,...,2,1,1,0,1,2,2,1.2,+10,105.6
5,2024-11-03,DAL,ORL,W (+23),0,8:34,1,3,.333,1,...,1,0,0,0,3,1,3,-1.8,-8,106.1
6,2024-11-04,DAL,IND,L (-7),Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,...,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,Did Not Play,117.3
7,2024-11-06,DAL,CHI,W (+20),0,13:29,4,10,.400,3,...,0,2,0,0,1,1,11,5.6,-5,117.9
8,2024-11-08,DAL,PHO,L (-1),0,3:29,0,0,NaN,0,...,0,0,0,0,0,0,0,0.0,-1,115.1
9,2024-11-10,DAL,DEN,L (-2),0,18:35,1,7,.143,0,...,2,3,1,0,1,1,2,0.2,0,115.0
10,2024-11-12,DAL,GSW,L (-3),0,18:57,1,2,.500,0,...,2,4,1,0,1,1,4,6.0,+16,108.4
11,2024-11-14,DAL,UTA,L (-2),0,22:05,3,6,.500,0,...,2,1,3,0,3,2,7,4.9,-8,120.1
12,2024-11-16,DAL,SAS,W (+17),0,18:30,4,9,.444,2,...,3,1,0,0,0,3,12,7.7,+5,113.5
13,2024-11-17,DAL,OKC,W (+2),0,24:06,6,9,.667,0,...,3,1,1,0,2,3,13,8.5,+6,103.7
14,2024-11-19,DAL,NOP,W (+41),0,19:20,4,12,.333,0,...,2,3,0,0,1,1,11,5.5,+13,118.6
15,2024-11-22,DAL,DEN,W (+3),0,13:14,3,9,.333,1,...,0,2,0,0,1,1,8,2.5,-16,115.0
16,2024-11-24,DAL,MIA,L (-5),0,9:15,0,3,.000,0,...,0,1,1,0,1,2,0,-2.2,-10,111.4
17,2024-11-25,DAL,ATL,W (+10),1,32:07,8,18,.444,2,...,3,2,3,0,6,2,23,11.3,-6,114.2
18,2024-11-27,DAL,NYK,W (+15),0,15:50,1,5,.200,1,...,1,0,0,0,1,0,5,1.2,+14,114.4
19,2024-11-30,DAL,UTA,W (+12),0,16:15,1,7,.143,0,...,2,2,2,0,3,3,4,-0.7,+1,120.1
21,2024-12-01,DAL,POR,W (+6),1,23:29,5,12,.417,3,...,3,1,1,0,0,1,13,8.8,-9,115.8
22,2024-12-03,DAL,MEM,W (+5),0,3:35,0,0,NaN,0,...,0,0,0,0,2,0,0,-2.0,-1,108.6
23,2024-12-05,DAL,WAS,W (+36),0,5:38,5,6,.833,2,...,1,0,0,0,0,1,13,10.7,+7,120.6

In [33]:
player_gamelog = pd.concat([player_gamelog, tgl_df], axis=1)
#player_gamelog = player_gamelog[(player_gamelog['PTS'] != 'Inactive') & (player_gamelog['PTS'] != 'Did Not Play') & (player_gamelog['MP'] != 'Did Not Dress')]
player_gamelog

,Date,Team,Opp,Result,GS,MP,FG,FGA,FG%,3P,...,PTS,GmSc,+/-,Opp DefRtg,Team_FG%,Team_3P%,Team_TRB,Team_AST,Team_STL,Team_BLK
0,2024-10-24,DAL,SAS,W (+11),0,19:40,3,6,.500,3,...,11,7.6,-5,113.5,.412,.432,50,27,9,5
1,2024-10-26,DAL,PHO,L (-12),0,13:16,0,4,.000,0,...,0,-2.9,-1,115.1,.398,.317,46,22,6,2
2,2024-10-28,DAL,UTA,W (+8),0,5:10,0,1,.000,0,...,0,-2.1,-4,120.1,.453,.282,50,27,9,12
3,2024-10-29,DAL,MIN,W (+6),0,4:25,1,1,1.000,0,...,2,1.7,+3,109.1,.484,.410,40,25,12,2
4,2024-10-31,DAL,HOU,L (-6),0,11:16,1,3,.333,0,...,2,1.2,+10,105.6,.459,.333,37,21,6,7
5,2024-11-03,DAL,ORL,W (+23),0,8:34,1,3,.333,1,...,3,-1.8,-8,106.1,.494,.313,53,25,8,5
7,2024-11-06,DAL,CHI,W (+20),0,13:29,4,10,.400,3,...,11,5.6,-5,117.9,.484,.316,47,33,11,4
8,2024-11-08,DAL,PHO,L (-1),0,3:29,0,0,NaN,0,...,0,0.0,-1,115.1,.513,.333,39,18,5,1
9,2024-11-10,DAL,DEN,L (-2),0,18:35,1,7,.143,0,...,2,0.2,0,115.0,.533,.303,42,29,7,5
10,2024-11-12,DAL,GSW,L (-3),0,18:57,1,2,.500,0,...,4,6.0,+16,108.4,.524,.324,40,26,6,1
11,2024-11-14,DAL,UTA,L (-2),0,22:05,3,6,.500,0,...,7,4.9,-8,120.1,.506,.308,30,25,11,10
12,2024-11-16,DAL,SAS,W (+17),0,18:30,4,9,.444,2,...,12,7.7,+5,113.5,.468,.258,53,26,9,7
13,2024-11-17,DAL,OKC,W (+2),0,24:06,6,9,.667,0,...,13,8.5,+6,103.7,.476,.407,53,18,4,5
14,2024-11-19,DAL,NOP,W (+41),0,19:20,4,12,.333,0,...,11,5.5,+13,118.6,.521,.452,48,26,12,7
15,2024-11-22,DAL,DEN,W (+3),0,13:14,3,9,.333,1,...,8,2.5,-16,115.0,.505,.370,44,24,11,5
16,2024-11-24,DAL,MIA,L (-5),0,9:15,0,3,.000,0,...,0,-2.2,-10,111.4,.419,.250,59,29,6,9
17,2024-11-25,DAL,ATL,W (+10),1,32:07,8,18,.444,2,...,23,11.3,-6,114.2,.500,.457,51,24,6,8
18,2024-11-27,DAL,NYK,W (+15),0,15:50,1,5,.200,1,...,5,1.2,+14,114.4,.565,.515,43,27,6,4
19,2024-11-30,DAL,UTA,W (+12),0,16:15,1,7,.143,0,...,4,-0.7,+1,120.1,.456,.385,48,30,12,6
21,2024-12-01,DAL,POR,W (+6),1,23:29,5,12,.417,3,...,13,8.8,-9,115.8,NaN,NaN,NaN,NaN,NaN,NaN
22,2024-12-03,DAL,MEM,W (+5),0,3:35,0,0,NaN,0,...,0,-2.0,-1,108.6,.552,.500,33,33,13,0
23,2024-12-05,DAL,WAS,W (+36),0,5:38,5,6,.833,2,...,13,10.7,+7,120.6,.481,.406,49,24,8,8
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,.539,.526,58,27,8,12

In [21]:
from selenium import webdriver
from selenium.webdriver.edge.service import Service
import pandas as pd
import time

# Define a function to scrape stats for an opponent
def fetch_opponent_stats(team_code):
    url = "https://www.basketball-reference.com/teams/"+team_code+"/2025.html"
    s = Service(r"C:\edgedriver_win64\msedgedriver.exe")
    driver=webdriver.Edge(service=s)
    driver.get(url)
    page_source = driver.page_source  # Get dynamically rendered HTML
    df = pd.read_html(page_source, header=0, attrs={'id': 'team_and_opponent'})[0]
    driver.close()
    opponent_row = df[df["Unnamed: 0"].str.contains("Team/G", na=False)]
    
    if opponent_row.empty:
        print(f"No Team/G stats found for {team_code}")
        return None
    
    # Extract relevant stats
    stats = {
        "Opp_FG%": float(opponent_row["FG%"].values[0]),
        "Opp_3P%": float(opponent_row["3P%"].values[0]),
        "Opp_TRB": float(opponent_row["TRB"].values[0]),
        "Opp_AST": float(opponent_row["AST"].values[0]),
        "Opp_STL": float(opponent_row["STL"].values[0]),
        "Opp_BLK": float(opponent_row["BLK"].values[0])
    }
    return stats

In [23]:
player_gamelog = player_gamelog[(player_gamelog['PTS'] != 'Inactive') & (player_gamelog['PTS'] != 'Did Not Play') & (player_gamelog['MP'] != 'Did Not Dress')]
player_gamelog

,Date,Team,Opp,Result,GS,MP,FG,FGA,FG%,3P,...,PTS,GmSc,+/-,Opp DefRtg,Team_FG%,Team_3P%,Team_TRB,Team_AST,Team_STL,Team_BLK
0,2024-10-22,BOS,NYK,W (+23),0,24:58,1,10,.100,1,...,3,-1.0,+7,114.6,.505,.475,40,33,6,3
1,2024-10-24,BOS,WAS,W (+20),0,27:57,5,11,.455,5,...,15,10.6,+11,119.9,.467,.378,49,21,7,3
2,2024-10-26,BOS,DET,W (+6),0,19:17,5,8,.625,5,...,19,16.6,-5,113.3,.422,.458,37,19,10,6
3,2024-10-28,BOS,MIL,W (+11),0,27:41,10,14,.714,8,...,28,25.8,+12,113.2,.494,.383,38,24,5,5
4,2024-10-30,BOS,IND,L (-3),0,38:34,5,14,.357,4,...,16,12.2,+8,117.9,.404,.333,51,23,11,5
5,2024-11-01,BOS,CHO,W (+15),0,27:50,1,6,.167,0,...,7,9.5,+13,114.3,.477,.310,41,21,12,5
6,2024-11-02,BOS,CHO,W (+10),0,29:06,8,15,.533,6,...,22,15.2,+7,114.3,.439,.308,44,23,4,4
7,2024-11-04,BOS,ATL,W (+30),0,25:29,7,12,.583,3,...,18,13.7,+21,114.9,.485,.327,50,27,15,7
8,2024-11-06,BOS,GSW,L (-6),0,32:10,5,13,.385,3,...,16,9.1,-8,108.8,.422,.352,47,22,5,3
9,2024-11-08,BOS,BRK,W (+4),0,33:38,6,11,.545,3,...,20,14.2,+11,117.5,.433,.264,39,23,7,9
10,2024-11-10,BOS,MIL,W (+6),0,22:50,6,10,.600,5,...,18,12.8,-8,113.2,.407,.380,42,27,5,2
11,2024-11-12,BOS,ATL,L (-1),0,25:17,2,8,.250,2,...,6,4.1,-9,114.9,.507,.400,34,28,7,5
12,2024-11-13,BOS,BRK,W (+25),0,36:13,8,13,.615,5,...,23,25.0,+14,117.5,.538,.478,45,35,7,6
13,2024-11-16,BOS,TOR,W (+3),0,23:53,2,8,.250,2,...,6,1.1,+6,115.7,.444,.344,42,30,2,6
14,2024-11-19,BOS,CLE,W (+3),0,25:43,5,9,.556,3,...,13,12.0,-14,110.9,.512,.537,42,32,4,4
15,2024-11-22,BOS,WAS,W (+12),0,22:33,3,6,.500,1,...,9,9.6,0,119.9,.424,.239,43,22,11,7
16,2024-11-24,BOS,MIN,W (+2),0,22:21,3,7,.429,1,...,8,7.2,-3,110.6,.425,.375,40,25,5,7
17,2024-11-25,BOS,LAC,W (+32),0,25:46,7,13,.538,6,...,20,18.1,+30,109.2,.511,.431,47,33,10,11
18,2024-11-29,BOS,CHI,W (+9),0,28:31,10,16,.625,7,...,29,26.8,+11,118.0,.500,.426,51,24,6,2
19,2024-12-01,BOS,CLE,L (-4),0,36:07,7,16,.438,3,...,24,18.7,-11,110.9,.400,.347,46,17,11,6
20,Date,Tm,Opp,NaN,GS,MP,FG,FGA,FG%,3P,...,PTS,GmSc,+/-,None,Team,Team,Team,Team,Team,Team
21,2024-12-02,BOS,MIA,W (+19),0,32:55,10,17,.588,5,...,25,23.1,+16,112.1,FG%,3P%,TRB,AST,STL,BLK
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,.438,.345,54,25,5,9

In [25]:
def convert_mp_to_minutes(mp):
    minutes, seconds = map(int, mp.split(':'))
    return minutes + seconds / 60
player_gamelog['MP'] = player_gamelog['MP'].apply(convert_mp_to_minutes)

ValueError: invalid literal for int() with base 10: 'MP'

In [43]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
import pandas as pd

df = player_gamelog  # Assuming 'player_gamelog' is the DataFrame

# Feature and Target Selection for Random Forest
X = df[['Opp DefRtg', 'MP']]  # Use 'Opp DefRtg' and 'MP' as features
y = df['PTS']  # Target variable is 'PTS'

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42,max_depth=None,max_features='sqrt',min_samples_leaf=1,min_samples_split=5)
rf_model.fit(X_train, y_train)

# Evaluate the Model
y_pred = rf_model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error (Random Forest Regressor with Opp DefRtg and MP): {mae}")

# Predict for new data
new_data = pd.DataFrame({
    'Opp DefRtg': [extract_defensive_rating(opponent)],  # Example input for Opp DefRtg
    'MP': [df.tail(5)['MP'].mean()]                      # Example input for MP
})
predicted_pts = rf_model.predict(new_data)
print(f"Predicted PTS: {predicted_pts[0]}")

Mean Absolute Error (Random Forest Regressor with Opp DefRtg and MP): 10.621862012987007
Predicted PTS: 28.575972222222212

In [45]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Load the dataset
df = player_gamelog  # Replace with your dataset path

# Data Cleaning
df = df.dropna(subset=['TRB', 'AST', 'FG', '3P', 'STL', 'BLK'])  # Remove rows with missing values
df = df[df['PTS'] != 'Inactive']  # Filter out non-active games

# Convert columns to numeric where applicable
df['TRB'] = pd.to_numeric(df['TRB'])
df['AST'] = pd.to_numeric(df['AST'])
df['FG'] = pd.to_numeric(df['FG'])
df['3P'] = pd.to_numeric(df['3P'])
df['STL'] = pd.to_numeric(df['STL'])
df['BLK'] = pd.to_numeric(df['BLK'])

# Feature and Target Selection
features = ['Opp DefRtg','Team_FG%','Team_3P%','Team_TRB','Team_AST','Team_STL','Team_BLK']  # Add other features as needed
targets = ['TRB', 'AST', 'FG', '3P', 'STL', 'BLK']  # Stat line to predict

X = df[features]
y = df[targets]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Model
model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

# Evaluate the Model
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")

# Predict for new data
print(opponent)
stats=fetch_opponent_stats(opponent)
new_data = pd.DataFrame({
    'Opp DefRtg': [extract_defensive_rating(opponent)],
    'Team_FG%': [stats['Opp_FG%']],
    'Team_3P%': [stats['Opp_3P%']],
    'Team_TRB': [stats['Opp_TRB']],
    'Team_AST': [stats['Opp_AST']],
    'Team_STL': [stats['Opp_STL']],
    'Team_BLK': [stats['Opp_BLK']]
})  # Example input
predicted_stats = model.predict(new_data)
print(f"Predicted Stats: {predicted_stats}")

Mean Absolute Error: 2.1879166666666667
MIA

C:\Users\trial\AppData\Local\Temp\ipykernel_10596\880682725.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(page_source, header=0, attrs={'id': 'team_and_opponent'})[0]

Predicted Stats: [[8.83 4.99 8.45 3.75 1.49 0.41]]

In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# Load the dataset
df = player_gamelog  # Replace with your dataset path

# Data Cleaning
df = df.dropna(subset=['TRB', 'AST', 'FG', '3P', 'STL', 'BLK'])  # Remove rows with missing values
df = df[df['PTS'] != 'Inactive']  # Filter out non-active games

# Convert columns to numeric where applicable
df['TRB'] = pd.to_numeric(df['TRB'])
df['AST'] = pd.to_numeric(df['AST'])
df['FG'] = pd.to_numeric(df['FG'])
df['3P'] = pd.to_numeric(df['3P'])
df['STL'] = pd.to_numeric(df['STL'])
df['BLK'] = pd.to_numeric(df['BLK'])

# Feature and Target Selection
features = ['Opp DefRtg','MP','Team_FG%','Team_3P%','Team_TRB','Team_AST','Team_STL','Team_BLK']  # Add other features as needed
targets = ['PTS','TRB', 'AST', 'FG', '3P', 'STL', 'BLK']  # Stat line to predict

X = df[features]
y = df[targets]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a Model
model = RandomForestRegressor(random_state=42,max_depth= None,min_samples_leaf= 4,min_samples_split= 10,n_estimators= 200)
model.fit(X_train, y_train)

# Evaluate the Model
y_pred = model.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
print(f"Mean Absolute Error: {mae}")

# Predict for new data
print(opponent)
stats=fetch_opponent_stats(opponent)
new_data = pd.DataFrame({
    'Opp DefRtg': [extract_defensive_rating(opponent)],
    'MP': [df.tail(5)['MP'].mean()],
    'Team_FG%': [stats['Opp_FG%']],
    'Team_3P%': [stats['Opp_3P%']],
    'Team_TRB': [stats['Opp_TRB']],
    'Team_AST': [stats['Opp_AST']],
    'Team_STL': [stats['Opp_STL']],
    'Team_BLK': [stats['Opp_BLK']]
})  # Example input
predicted_stats = model.predict(new_data)
print(f"Predicted Stats: {predicted_stats}")

Mean Absolute Error: 1.8122424941130293
DEN

C:\Users\trial\AppData\Local\Temp\ipykernel_21668\880682725.py:13: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(page_source, header=0, attrs={'id': 'team_and_opponent'})[0]

Predicted Stats: [[17.17393269  3.90960699  2.49112729  5.94406136  2.10457479  0.97766132
   0.76207021]]

In [69]:
injuries_df=pd.DataFrame()
url='https://www.basketball-reference.com/teams/'+team+'/2025.html'
s = Service(r"C:\edgedriver_win64\msedgedriver.exe")
driver=webdriver.Edge(service=s)
driver.get(url)
page_source = driver.page_source  # Get dynamically rendered HTML
injuries_df = pd.read_html(page_source, header=0, attrs={'id': 'injuries'})[0]
driver.close()
name=roster_df.iloc[player-1]['Player']
if name in list(injuries_df['Player'].values):
    print("Player listed in injury report")

C:\Users\trial\AppData\Local\Temp\ipykernel_19656\3585589472.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  injuries_df = pd.read_html(page_source, header=0, attrs={'id': 'injuries'})[0]

In [29]:
player_split_df=pd.DataFrame()
url='https://www.basketball-reference.com/players/c/'+name+'/splits/2025'
player_split_df=pd.read_html(url,header=1,attrs={'id':'splits'})[0]
season_avg_row=player_split_df.iloc[0]
print("Minutes:",season_avg_row['MP.1'])
print("Pts:",season_avg_row['PTS.1'])
print("Reb:",season_avg_row['TRB.1'])
print("Ast:",season_avg_row['AST.1'])
print("Stl:",season_avg_row['STL']/season_avg_row['G'])
print("Blk:",season_avg_row['BLK']/season_avg_row['G'])
print("FG%: ",season_avg_row['FG%'])
print("3P%: ",season_avg_row['3P%'])

Split        NaN
Value      Total
G             21
GS            21
MP           764
FG           192
FGA          423
3P            83
3PA          222
FT           130
FTA          162
ORB           10
TRB          181
AST          118
STL           28
BLK           12
TOV           62
PF            51
PTS          597
&nbsp        NaN
FG%         .454
3P%         .374
FT%         .802
&nbsp.1      NaN
TS%         .604
USG%        31.7
ORtg         119
DRtg         109
+/-        +13.6
&nbsp.2      NaN
MP.1        36.4
PTS.1       28.4
TRB.1        8.6
AST.1        5.6
Name: 0, dtype: object

In [35]:
print("Minutes:",season_avg_row['MP.1'])
print("Pts:",season_avg_row['PTS.1'])
print("Reb:",season_avg_row['TRB.1'])
print("Ast:",season_avg_row['AST.1'])
print("Stl: {:.2f}".format(float(season_avg_row['STL']) / float(season_avg_row['G'])))
print("Blk: {:.2f}".format(float(season_avg_row['BLK']) / float(season_avg_row['G'])))
print("FG%: ",season_avg_row['FG%'])
print("3P%: ",season_avg_row['3P%'])

Minutes: 36.4
Pts: 28.4
Reb: 8.6
Ast: 5.6
Stl: 1.33
Blk: 0.57
FG%:  .454
3P%:  .374